import type { Metadata } from "next";
import "./globals.css";
import { Red_Hat_Display } from "next/font/google";
import localFont from "next/font/local";
import { Providers } from "@/store/Provider";

const redHatDisplay = Red_Hat_Display({
   variable: "--font-red-hat-display",
   subsets: ["latin"],
   weight: ["300", "400", "500", "600", "700", "800", "900"],
   display: "swap",
});

const proximaNova = localFont({
   src: [
      {
         path: "./fonts/Proxima_Nova_Regular.otf",
         weight: "400",
         style: "normal",
      },
      {
         path: "./fonts/Proxima_Nova_Semibold.otf",
         weight: "500",
         style: "normal",
      },
      {
         path: "./fonts/Proxima_Nova_Bold.otf",
         weight: "600",
         style: "normal",
      },
      {
         path: "./fonts/Proxima_Nova_Black.otf",
         weight: "800",
         style: "normal",
      },
      {
         path: "./fonts/ProximaNova-ExtrabldIt.otf",
         weight: "900",
         style: "normal",
      },
   ],
   variable: "--font-proxima-nova",
   display: "swap",
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={`${proximaNova.variable} ${redHatDisplay.variable} antialiased`}>
            <Providers>{children}</Providers>
         </body>
      </html>
   );
}
